# Generated by Django 4.2.30 on 2026-05-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('sport', models.CharField(max_length=50)),
                ('founded_year', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
